[2024-01-31T10:23:02.976+0000] {scheduler_job_runner.py:781} ERROR - Executor reports task instance <TaskInstance: data_ingestion_gcs_dag.yellow_tripdata_2022-01.parquet_to_gcs_task scheduled__2024-01-30T00:00:00+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
